### PR TITLE
Added persistent button state with chrome sync, fix min-width on labels

### PR DESCRIPTION
**Pull request by leocb**
Hi! Here are some changes I've made to your extension:
+ Persistent button state using chrome sync; Now the "storage" permission is required, but it should increase the usability by a lot!
* Changed init function to act immediately and then check at interval (page changes)
* Increased check interval to 3 seconds
* Fixed the min-width on labels following the latest Trello update
* Lint

Also, have you published the current version (1.1.0)? I didn't get the update and the chrome store still says 1.0.1

### CODE REVIEW

**Comment by laander** [comment]
@leocb Good stuff man! Thanks a ton for the update 👏

My only wish is to rename the `state` attribute on the button to `data-state` in order to follow the [HTML5 spec](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes).

Also, do you know what will happen if we add the "storage" permission requirement in an update? Will Chrome show a confirm prompt upon updating the extension?

Just checked and you were right: I forgot to publish the `v1.1.0` update in the Chrome web store console. Shitty UX in there. Oh well, released now! 🎉

**Comment by leocb** [comment]
@laander Thanks! 😄 
I'll rename the attribute as soon as I can, but I'll only have access to my dev pc again on thursday, so it'll take a while haha

I didn't think about update process, but [the docs](https://developer.chrome.com/extensions/permission_warnings#nowarning) says this won't be a problem in the case of this particular permission

I also caught a bug with the button state when changing boards (reloading the page works fine) - I'll fix it before sending another commit.

**Comment by leocb** [comment]
Hi! I made some modifications, and I believe its ready to merge now:

- Changed button "state" attribute name to "data-state"
- Now using the js "dataset" property to get and set the state
- Fixed a bug where the state would toggle when changing boards
- Now we use let instead of var
- No more semicolons :+1:

**Comment by leocb** [comment]
don't forget about me o/
:)

**Comment by laander** [comment]
Sorry @leocb, too many side projects, too little time 😅 

I'll merge and release. Thanks again!

**Pull request merged**
